// Generated by CoffeeScript 1.6.3
/*
# nodejs-express-mongoose-demo
# Copyright(c) 2013 Madhusudhan Srinivasa <madhums8@gmail.com>
# MIT Licensed
*/


(function() {
  var app, auth, config, env, exports, express, fs, models_path, mongoose, passport, port;

  express = require('express');

  fs = require('fs');

  passport = require('passport');

  env = process.env.NODE_ENV || 'development';

  config = require('./config/config')[env];

  auth = require('./config/middlewares/authorization');

  mongoose = require('mongoose');

  mongoose.connect(config.db);

  models_path = __dirname + '/models';

  fs.readdirSync(models_path).forEach(function(file) {
    return require(models_path + '/' + file);
  });

  require('./config/passport')(passport, config);

  app = express();

  require('./config/express')(app, config, passport);

  require('./config/routes')(app, passport, auth);

  port = process.env.PORT || 3000;

  app.listen(port);

  console.log("Express app started on port " + port);

  exports = module.exports = app;

}).call(this);
