// Generated by CoffeeScript 1.6.3
(function() {
  var notifier, path, rootPath, templatePath;

  path = require('path');

  rootPath = process.cwd();

  console.log("[config::rootPath] " + rootPath);

  templatePath = path.normalize(__dirname + '/../app/mailer/templates');

  notifier = {
    APN: false,
    email: false,
    actions: ['comment'],
    tplPath: templatePath,
    postmarkKey: 'POSTMARK_KEY',
    parseAppId: 'PARSE_APP_ID',
    parseApiKey: 'PARSE_MASTER_KEY'
  };

  module.exports = {
    development: {
      db: 'mongodb://localhost/cmbase_dev',
      root: rootPath,
      notifier: notifier,
      app: {
        name: 'CMBase user system'
      }
    },
    test: {
      db: 'mongodb://localhost/cmbase_test',
      root: rootPath,
      notifier: notifier,
      app: {
        name: 'CMBase user system'
      }
    },
    production: {
      db: 'mongodb://localhost/cmbase_prod',
      root: rootPath,
      notifier: notifier,
      app: {
        name: 'CMBase user system'
      }
    }
  };

}).call(this);
