// Generated by CoffeeScript 1.6.3
(function() {
  var async;

  async = require("async");

  module.exports = function(app, passport, auth) {
    var home, users;
    users = require("../controllers/users");
    app.get('/login', users.login);
    app.get('/signup', users.signup);
    app.get('/logout', users.logout);
    app.post('/users', users.create);
    app.post('/api/signup', (function(req, res, next) {
      return (req.speak_as = "json") && next();
    }), users.create);
    app.post('/users/session', passport.authenticate('local', {
      failureRedirect: '/login',
      failureFlash: 'Invalid email or password.'
    }), users.session);
    app.post('/api/login', passport.authenticate('local', {
      session: false
    }), function(req, res) {
      return res.json({
        id: req.user.id,
        success: true
      });
    });
    app.post('/api/change_password', passport.authenticate('local', {
      session: false
    }), (function(req, res, next) {
      return (req.speak_as = "json") && next();
    }), users.changePassword);
    app.get('/users/:userId', users.show);
    home = require("../controllers/home");
    return app.get('/', home.index);
  };

}).call(this);
